const electronicsProducts = [
  {
    name: 'Smart watches',
    price: 19,
    originalPrice: 30,
    image: '/assets/smart-watches.png',
    description: 'Modern smartwatch with fitness tracking and smart notifications.',
    category: 'Home & Outdoor',
    stock: 70,
    rating: 8.3,
    orders: 320,
    reviews: 102,
    sold: 280,
    featured: true,
    shipping: 'Free Shipping',
    specs: {
      Price: '$19',
      Type: 'Smart Watch',
      Material: 'Aluminum',
      Design: 'Sport',
      Protection: 'Water resistant',
      Warranty: '1 year',
    },
    specTable: [
      { label: 'Battery', value: '7 days' },
      { label: 'Display', value: 'AMOLED' },
      { label: 'Connectivity', value: 'Bluetooth 5.2' },
    ],
    pricingTiers: [
      { range: '1-20 pcs', price: 19 },
      { range: '20+ pcs', price: 16 },
    ],
    features: ['Smart Features', 'Wireless Connectivity', 'Portable Design'],
    seller: {
      name: 'WearTech',
      location: 'China',
      verified: true,
    },
  },

  {
    name: 'Cameras',
    price: 89,
    originalPrice: 120,
    image: '/assets/cameras.png',
    description: 'Professional digital camera suitable for photography and travel.',
    category: 'Electronics',
    stock: 22,
    rating: 8.7,
    orders: 145,
    reviews: 56,
    sold: 121,
    featured: true,
    shipping: 'Free Shipping',
    specs: {
      Price: '$89',
      Type: 'Camera',
      Material: 'Metal',
      Design: 'Compact',
      Protection: 'Refund available',
      Warranty: '2 years',
    },
    specTable: [
      { label: 'Resolution', value: '24MP' },
      { label: 'Video', value: '4K' },
      { label: 'Zoom', value: '10x Optical' },
    ],
    pricingTiers: [
      { range: '1-10 pcs', price: 89 },
      { range: '10+ pcs', price: 82 },
    ],
    features: ['High Performance', 'Portable Design', 'Smart Features'],
    seller: {
      name: 'Photo Gear',
      location: 'Japan',
      verified: true,
    },
  },

  {
    name: 'Headphones',
    price: 10,
    originalPrice: 20,
    image: '/assets/headphones.png',
    description: 'Comfortable headphones with immersive sound and deep bass.',
    category: 'Mobile accessory',
    stock: 90,
    rating: 8.0,
    orders: 400,
    reviews: 120,
    sold: 350,
    featured: false,
    shipping: 'Free Shipping',
    specs: {
      Price: '$10',
      Type: 'Headphones',
      Material: 'Plastic',
      Design: 'Over-ear',
      Protection: '7-day return',
      Warranty: '6 months',
    },
    specTable: [
      { label: 'Connectivity', value: 'Wireless' },
      { label: 'Battery', value: '20 hours' },
      { label: 'Noise Cancellation', value: 'Passive' },
    ],
    pricingTiers: [
      { range: '1-30 pcs', price: 10 },
      { range: '30+ pcs', price: 8 },
    ],
    features: ['Wireless Connectivity', 'Portable Design', 'Premium Build'],
    seller: {
      name: 'Audio Hub',
      location: 'Germany',
      verified: false,
    },
  }
]

export default electronicsProducts