const electronicsProducts = [
  {
    name: 'Smart watches',
    price: 19,
    originalPrice: 30,
    image: '/assets/smart-watches-2.png',
    description:
      'Modern smartwatch with fitness tracking and smart notifications.',
    category: 'Electronics',
    stock: 70,
    rating: 8.3,
    orders: 320,
    reviews: 102,
    sold: 280,
    featured: true,
    discount: 36,
    shipping: 'Free Shipping',
    specs: {
      Price: '$19',
      Type: 'Smart Watch',
      Material: 'Aluminum',
      Design: 'Sport',
      Protection: 'Water resistant',
      Warranty: '1 year',
    },
    specTable: [
      { label: 'Battery', value: '7 days' },
      { label: 'Display', value: 'AMOLED' },
      { label: 'Connectivity', value: 'Bluetooth 5.2' },
    ],
    pricingTiers: [
      { range: '1-20 pcs', price: 19 },
      { range: '20+ pcs', price: 16 },
    ],
    features: ['Heart rate monitor', 'Sleep tracking', 'Notifications'],
    seller: {
      name: 'WearTech',
      location: 'China',
      verified: true,
    },
  },

  {
    name: 'Cameras',
    price: 89,
    originalPrice: 120,
    image: '/assets/cameras.png',
    description:
      'Professional digital camera suitable for photography and travel.',
    category: 'Electronics',
    stock: 22,
    rating: 8.7,
    orders: 145,
    reviews: 56,
    sold: 121,
    featured: true,
    discount: 26,
    shipping: 'Free Shipping',
    specs: {
      Price: '$89',
      Type: 'Camera',
      Material: 'Metal',
      Design: 'Compact',
      Protection: 'Refund available',
      Warranty: '2 years',
    },
    specTable: [
      { label: 'Resolution', value: '24MP' },
      { label: 'Video', value: '4K' },
      { label: 'Zoom', value: '10x Optical' },
    ],
    pricingTiers: [
      { range: '1-10 pcs', price: 89 },
      { range: '10+ pcs', price: 82 },
    ],
    features: ['4K video', 'Portable body', 'Fast autofocus'],
    seller: {
      name: 'Photo Gear',
      location: 'Japan',
      verified: true,
    },
  },

  {
    name: 'Headphones',
    price: 10,
    originalPrice: 20,
    image: '/assets/headphones.png',
    description:
      'Comfortable headphones with immersive sound and deep bass.',
    category: 'Audio',
    stock: 90,
    rating: 8.0,
    orders: 400,
    reviews: 120,
    sold: 350,
    featured: false,
    discount: 50,
    shipping: 'Free Shipping',
    specs: {
      Price: '$10',
      Type: 'Headphones',
      Material: 'Plastic',
      Design: 'Over-ear',
      Protection: '7-day return',
      Warranty: '6 months',
    },
    specTable: [
      { label: 'Connectivity', value: 'Wireless' },
      { label: 'Battery', value: '20 hours' },
      { label: 'Noise Cancellation', value: 'Passive' },
    ],
    pricingTiers: [
      { range: '1-30 pcs', price: 10 },
      { range: '30+ pcs', price: 8 },
    ],
    features: ['Deep bass', 'Comfort fit', 'Long battery'],
    seller: {
      name: 'Audio Hub',
      location: 'Germany',
      verified: false,
    },
  },

  {
    name: 'Gaming set',
    price: 35,
    originalPrice: 50,
    image: '/assets/gaming-set.png',
    description:
      'Complete gaming accessories set for PC and console gamers.',
    category: 'Gaming',
    stock: 35,
    rating: 8.6,
    orders: 190,
    reviews: 77,
    sold: 160,
    featured: true,
    discount: 30,
    shipping: 'Free Express Shipping',
    specs: {
      Price: '$35',
      Type: 'Gaming Accessories',
      Material: 'Plastic & RGB',
      Design: 'Gaming',
      Protection: '30-day return',
      Warranty: '1 year',
    },
    specTable: [
      { label: 'Keyboard', value: 'Mechanical' },
      { label: 'Mouse DPI', value: '12000 DPI' },
      { label: 'Lighting', value: 'RGB' },
    ],
    pricingTiers: [
      { range: '1-15 pcs', price: 35 },
      { range: '15+ pcs', price: 30 },
    ],
    features: ['RGB lighting', 'Mechanical keys', 'Gaming mouse'],
    seller: {
      name: 'GamePro',
      location: 'USA',
      verified: true,
    },
  },

  {
    name: 'Laptops & PC',
    price: 340,
    originalPrice: 420,
    image: '/assets/laptops-and-pc.png',
    description:
      'Reliable laptops and desktop PCs for work, study, and gaming.',
    category: 'Computers',
    stock: 15,
    rating: 9.0,
    orders: 250,
    reviews: 98,
    sold: 210,
    featured: true,
    discount: 19,
    shipping: 'Free Shipping',
    specs: {
      Price: '$340',
      Type: 'Computer',
      Material: 'Aluminum',
      Design: 'Modern',
      Protection: 'Refund available',
      Warranty: '2 years',
    },
    specTable: [
      { label: 'Processor', value: 'Intel Core i7' },
      { label: 'RAM', value: '16GB' },
      { label: 'Storage', value: '512GB SSD' },
    ],
    pricingTiers: [
      { range: '1-5 pcs', price: 340 },
      { range: '5+ pcs', price: 320 },
    ],
    features: ['Fast performance', 'SSD storage', 'HD display'],
    seller: {
      name: 'Compute World',
      location: 'United States',
      verified: true,
    },
  },

  {
    name: 'Smartphones',
    price: 19,
    originalPrice: 35,
    image: '/assets/smartphones.png',
    description:
      'Affordable smartphone with modern features and long battery life.',
    category: 'Smartphones',
    stock: 80,
    rating: 8.2,
    orders: 500,
    reviews: 165,
    sold: 430,
    featured: true,
    discount: 46,
    shipping: 'Free Shipping',
    specs: {
      Price: '$19',
      Type: 'Smartphone',
      Material: 'Glass & Aluminum',
      Design: 'Slim',
      Protection: 'Screen protection',
      Warranty: '1 year',
    },
    specTable: [
      { label: 'Display', value: '6.5-inch HD' },
      { label: 'Battery', value: '5000mAh' },
      { label: 'Storage', value: '128GB' },
    ],
    pricingTiers: [
      { range: '1-20 pcs', price: 19 },
      { range: '20+ pcs', price: 16 },
    ],
    features: ['Fast charging', 'Large display', 'Dual camera'],
    seller: {
      name: 'Mobile Store',
      location: 'South Korea',
      verified: true,
    },
  },

  {
    name: 'Electric kettle',
    price: 240,
    originalPrice: 290,
    image: '/assets/electric-kettle.png',
    description:
      'Premium electric kettle with fast boiling and temperature control.',
    category: 'Home Appliances',
    stock: 25,
    rating: 8.5,
    orders: 130,
    reviews: 54,
    sold: 112,
    featured: false,
    discount: 17,
    shipping: 'Free Shipping',
    specs: {
      Price: '$240',
      Type: 'Electric Kettle',
      Material: 'Stainless Steel',
      Design: 'Minimal',
      Protection: 'Refund available',
      Warranty: '2 years',
    },
    specTable: [
      { label: 'Capacity', value: '1.8L' },
      { label: 'Power', value: '1800W' },
      { label: 'Temperature Control', value: 'Yes' },
    ],
    pricingTiers: [
      { range: '1-10 pcs', price: 240 },
      { range: '10+ pcs', price: 225 },
    ],
    features: ['Fast boil', 'Auto shut-off', 'Premium steel body'],
    seller: {
      name: 'Kitchen Tech',
      location: 'Germany',
      verified: true,
    },
  },
]

export default electronicsProducts