const homeOutdoorProducts = [
  {
    name: 'Soft chairs',
    price: 19,
    originalPrice: 29,
    image: '/assets/soft-chairs.png',
    description:
      'Comfortable soft chairs perfect for living rooms, lounges, and office spaces.',
    category: 'Home & Outdoor',
    stock: 45,
    rating: 8.2,
    orders: 120,
    reviews: 48,
    sold: 98,
    featured: false,
    discount: 34,
    shipping: 'Free Shipping',
    specs: {
      Price: '$19',
      Type: 'Chair',
      Material: 'Fabric & Wood',
      Design: 'Modern',
      Protection: '7-day return',
      Warranty: '1 year',
    },
    specTable: [
      { label: 'Material', value: 'Soft Fabric' },
      { label: 'Frame', value: 'Solid Wood' },
      { label: 'Weight Capacity', value: '120kg' },
    ],
    pricingTiers: [
      { range: '1-10 pcs', price: 19 },
      { range: '10-50 pcs', price: 17 },
    ],
    features: ['Soft cushion', 'Modern design', 'Lightweight'],
    seller: {
      name: 'Home Comfort',
      location: 'Turkey',
      verified: true,
    },
  },

  {
    name: 'Sofa & chair',
    price: 19,
    originalPrice: 35,
    image: '/assets/sofa-and-chairs.png',
    description:
      'Stylish sofa and chair combo designed for modern interiors.',
    category: 'Home & Outdoor',
    stock: 30,
    rating: 8.5,
    orders: 90,
    reviews: 37,
    sold: 72,
    featured: true,
    discount: 45,
    shipping: 'Free Shipping',
    specs: {
      Price: '$19',
      Type: 'Furniture Set',
      Material: 'Leather',
      Design: 'Luxury',
      Protection: '30-day return',
      Warranty: '2 years',
    },
    specTable: [
      { label: 'Seats', value: '3 + 1' },
      { label: 'Material', value: 'Premium Leather' },
      { label: 'Color', value: 'Brown' },
    ],
    pricingTiers: [
      { range: '1-5 pcs', price: 19 },
      { range: '5+ pcs', price: 17 },
    ],
    features: ['Premium leather', 'Comfort foam', 'Elegant finish'],
    seller: {
      name: 'Urban Living',
      location: 'Italy',
      verified: true,
    },
  },

  {
    name: 'Kitchen dishes',
    price: 19,
    originalPrice: 25,
    image: '/assets/kitchen-dishes.png',
    description:
      'Durable kitchen dish set suitable for daily family use.',
    category: 'Kitchen',
    stock: 100,
    rating: 8.0,
    orders: 230,
    reviews: 81,
    sold: 190,
    featured: false,
    discount: 24,
    shipping: 'Free Shipping',
    specs: {
      Price: '$19',
      Type: 'Kitchenware',
      Material: 'Ceramic',
      Design: 'Classic',
      Protection: 'Refund available',
      Warranty: '6 months',
    },
    specTable: [
      { label: 'Pieces', value: '12' },
      { label: 'Dishwasher Safe', value: 'Yes' },
      { label: 'Microwave Safe', value: 'Yes' },
    ],
    pricingTiers: [
      { range: '1-20 pcs', price: 19 },
      { range: '20+ pcs', price: 16 },
    ],
    features: ['Heat resistant', 'Easy cleaning', 'Elegant design'],
    seller: {
      name: 'Kitchen World',
      location: 'China',
      verified: true,
    },
  },

  {
    name: 'Kitchen mixer',
    price: 100,
    originalPrice: 129,
    image: '/assets/kitchen-mixer.png',
    description:
      'Powerful kitchen mixer ideal for baking and food preparation.',
    category: 'Kitchen Appliances',
    stock: 18,
    rating: 8.8,
    orders: 140,
    reviews: 59,
    sold: 121,
    featured: true,
    discount: 22,
    shipping: 'Free Express Shipping',
    specs: {
      Price: '$100',
      Type: 'Mixer',
      Material: 'Stainless Steel',
      Design: 'Compact',
      Protection: '30-day return',
      Warranty: '2 years',
    },
    specTable: [
      { label: 'Power', value: '1000W' },
      { label: 'Speed Levels', value: '6' },
      { label: 'Bowl Capacity', value: '5L' },
    ],
    pricingTiers: [
      { range: '1-10 pcs', price: 100 },
      { range: '10+ pcs', price: 92 },
    ],
    features: ['Powerful motor', 'Easy controls', 'Low noise'],
    seller: {
      name: 'Chef Equip',
      location: 'Germany',
      verified: true,
    },
  },

  {
    name: 'Blenders',
    price: 39,
    originalPrice: 55,
    image: '/assets/blenders.png',
    description:
      'High-speed blender suitable for smoothies, juices, and food prep.',
    category: 'Kitchen Appliances',
    stock: 40,
    rating: 8.4,
    orders: 175,
    reviews: 62,
    sold: 150,
    featured: false,
    discount: 29,
    shipping: 'Free Shipping',
    specs: {
      Price: '$39',
      Type: 'Blender',
      Material: 'Plastic & Steel',
      Design: 'Portable',
      Protection: '7-day return',
      Warranty: '1 year',
    },
    specTable: [
      { label: 'Power', value: '700W' },
      { label: 'Jar Capacity', value: '1.5L' },
      { label: 'Blades', value: 'Stainless Steel' },
    ],
    pricingTiers: [
      { range: '1-15 pcs', price: 39 },
      { range: '15+ pcs', price: 34 },
    ],
    features: ['Sharp blades', 'Easy cleaning', 'Compact size'],
    seller: {
      name: 'Blend Master',
      location: 'Malaysia',
      verified: false,
    },
  },

  {
    name: 'Home appliance',
    price: 19,
    originalPrice: 30,
    image: '/assets/home-appliance.jpg',
    description:
      'Multi-purpose home appliance designed for everyday convenience.',
    category: 'Home Appliances',
    stock: 50,
    rating: 7.9,
    orders: 110,
    reviews: 39,
    sold: 90,
    featured: false,
    discount: 37,
    shipping: 'Free Shipping',
    specs: {
      Price: '$19',
      Type: 'Appliance',
      Material: 'ABS Plastic',
      Design: 'Compact',
      Protection: 'Refund available',
      Warranty: '1 year',
    },
    specTable: [
      { label: 'Voltage', value: '220V' },
      { label: 'Usage', value: 'Home' },
      { label: 'Energy Saving', value: 'Yes' },
    ],
    pricingTiers: [
      { range: '1-20 pcs', price: 19 },
      { range: '20+ pcs', price: 15 },
    ],
    features: ['Compact size', 'Energy efficient', 'Easy setup'],
    seller: {
      name: 'Smart Home Ltd',
      location: 'Singapore',
      verified: true,
    },
  },

  {
    name: 'Coffee maker',
    price: 10,
    originalPrice: 18,
    image: '/assets/coffee-maker.png',
    description:
      'Compact coffee maker for brewing fresh coffee quickly at home.',
    category: 'Kitchen Appliances',
    stock: 60,
    rating: 8.1,
    orders: 210,
    reviews: 70,
    sold: 180,
    featured: true,
    discount: 44,
    shipping: 'Free Shipping',
    specs: {
      Price: '$10',
      Type: 'Coffee Maker',
      Material: 'Plastic & Steel',
      Design: 'Minimal',
      Protection: '7-day return',
      Warranty: '1 year',
    },
    specTable: [
      { label: 'Capacity', value: '1L' },
      { label: 'Brewing Time', value: '5 min' },
      { label: 'Power', value: '600W' },
    ],
    pricingTiers: [
      { range: '1-25 pcs', price: 10 },
      { range: '25+ pcs', price: 8 },
    ],
    features: ['Quick brewing', 'Easy cleaning', 'Compact body'],
    seller: {
      name: 'CafeTech',
      location: 'France',
      verified: true,
    },
  },
]

export default homeOutdoorProducts